"""Orchestrate document generation and RECORD file persistence (Task 7).

Calls the docx generator, persists the bytes via ``file_store.persist_record``,
and wires a ``files`` row so the document is a proper RECORD file.  Also
provides a lookup helper used by the download endpoint — never accepts raw
file paths from the client; always resolves through the DB.

Also manages temporary PDF files for HR and Interviewer roles, stored
on disk and auto-deleted when the interview is marked as done.
"""

import logging
import os

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import File, Interview, QuestionEvaluationKey
from app.models.schemas import InterviewResult
from app.services.document_generator import (
    generate_answer_key,
    generate_docx,
    generate_pdf,
    generate_question_sheet,
    delete_pdf,
    question_sheet_layout_metadata,
)
from app.services.file_store import delete_stored_file, persist_record

logger = logging.getLogger(__name__)

# Lowercase API names -> Postgres ENUM values stored in ``files.file_type``.
# Documents generated by this module and the MCQ sheet service.
DOCUMENT_FILE_TYPES = {"question_sheet", "answer_key", "mcq_sheet"}
_DB_FILE_TYPES = {
    "question_sheet": "QUESTION_SHEET",
    "answer_key": "ANSWER_KEY",
    "mcq_sheet": "MCQ_SHEET",
}

# Temporary PDF storage directory
PDF_STORAGE_DIR = "generated_pdfs"


def file_type_to_db(file_type: str) -> str | None:
    """Map a lowercase API file_type to its DB ENUM value (or None)."""
    return _DB_FILE_TYPES.get(file_type)


def db_to_file_type(db_value: str) -> str:
    """Map a DB ENUM value back to its lowercase API name."""
    for api_name, enum_value in _DB_FILE_TYPES.items():
        if enum_value == db_value:
            return api_name
    return db_value


def generate_and_persist_documents(
    session: Session,
    *,
    interview: Interview,
    result: InterviewResult,
) -> dict[str, str]:
    """Generate both RECORD documents and persist them under the interview's
    upload directory, inserting ``files`` rows.
    Returns a ``{file_type: file_path}`` mapping (lowercase API names) of
    what was persisted.  Idempotent: any previously generated QUESTION_SHEET /
    ANSWER_KEY rows for the same interview — and their files — are
    removed first, so crash-recovery re-runs never leave duplicate documents.
    """
    interview_id_str = interview.interview_id
    interview_pk = interview.id
    generated: dict[str, str] = {}

    # Wipe any prior documents for this interview first — a deliberate,
    # logged regeneration, so crash-recovery re-runs are clean.
    existing = list(
        session.scalars(
            select(File).where(
                File.interview_id == interview_pk,
                File.file_type.in_(list(_DB_FILE_TYPES.values())),
            )
        ).all()
    )
    for old in existing:
        delete_stored_file(old.file_path)
        session.delete(old)
    session.flush()

    for file_type, generator_fn in [
        ("question_sheet", generate_question_sheet),
        ("answer_key", generate_answer_key),
    ]:
        docx_bytes = generator_fn(result, interview_id=interview_id_str)
        file_path = persist_record(
            docx_bytes,
            interview_id=interview_id_str,
            file_type=file_type,
            ext=".docx",
        )
        layout = (
            question_sheet_layout_metadata(result)
            if file_type == "question_sheet"
            else None
        )
        session.add(
            File(
                interview_id=interview_pk,
                file_type=_DB_FILE_TYPES[file_type],
                file_path=file_path,
                layout_metadata=layout,
            )
        )
        generated[file_type] = file_path
        logger.info(
            "Persisted %s for interview %s -> %s",
            file_type, interview_id_str, file_path,
        )

    session.flush()
    return generated


def generate_interview_pdfs(
    session: Session,
    *,
    interview: Interview,
    result: InterviewResult,
) -> dict[str, str]:
    """Generate temporary PDFs for HR and Interviewer roles.

    Returns a ``{role: filepath}`` mapping. Paths are stored temporarily
    and should be deleted when the interview is marked as done.
    """
    interview_id_str = interview.interview_id
    os.makedirs(PDF_STORAGE_DIR, exist_ok=True)
    pdf_paths: dict[str, str] = {}

    for role in ("interviewer", "hr"):
        filepath = generate_pdf(
            result,
            role=role,
            interview_id=interview_id_str,
            output_dir=PDF_STORAGE_DIR,
        )
        pdf_paths[role] = filepath
        logger.info(
            "Generated temporary PDF for %s: %s", role, filepath,
        )

    return pdf_paths


def store_pdf_paths(session: Session, interview_id: int, pdf_paths: dict[str, str]) -> None:
    """Store PDF file paths as File records (type PDF_TEMP) for tracking."""
    from app.db.models import File as DBFile
    from app.db.models import FileTypeType

    for role, filepath in pdf_paths.items():
        file_type_str = f"PDF_{role.upper()}"
        # Map role to a file_type enum value
        enum_value = f"PDF_{role.upper()}"
        try:
            session.add(
                DBFile(
                    interview_id=interview_id,
                    file_type=enum_value,
                    file_path=filepath,
                )
            )
        except Exception as e:
            logger.warning("Could not store PDF record for %s: %s", role, e)
    session.flush()


def get_pdf_paths(session: Session, interview_pk: int) -> dict[str, str]:
    """Get temporary PDF file paths for an interview."""
    from app.db.models import File as DBFile
    from sqlalchemy import or_ as sql_or

    files = list(
        session.scalars(
            select(DBFile).where(
                DBFile.interview_id == interview_pk,
                DBFile.file_type.like("PDF_%"),
            )
        ).all()
    )
    result: dict[str, str] = {}
    for f in files:
        role = f.file_type.replace("PDF_", "").lower()
        result[role] = f.file_path
    return result


def delete_interview_pdfs(session: Session, interview_pk: int) -> None:
    """Delete all temporary PDF files for an interview and their DB records."""
    from app.db.models import File as DBFile

    files = list(
        session.scalars(
            select(DBFile).where(
                DBFile.interview_id == interview_pk,
                DBFile.file_type.like("PDF_%"),
            )
        ).all()
    )
    for f in files:
        delete_pdf(f.file_path)
        session.delete(f)
    session.flush()
    logger.info("Deleted all temporary PDFs for interview_pk=%d", interview_pk)


def get_document_file(
    session: Session,
    *,
    interview_pk: int,
    file_type: str,
) -> File | None:
    """Look up a ``files`` row by interview PK and API file_type."""
    db_type = file_type_to_db(file_type)
    if db_type is None:
        return None
    return session.scalar(
        select(File).where(
            File.interview_id == interview_pk,
            File.file_type == db_type,
        )
    )


def list_documents(
    session: Session,
    *,
    interview_pk: int,
) -> list[File]:
    """Return all ``files`` rows for an interview whose ``file_type`` is one
    of the two documents this module can generate."""
    return list(
        session.scalars(
            select(File).where(
                File.interview_id == interview_pk,
                File.file_type.in_(list(_DB_FILE_TYPES.values())),
            )
        ).all()
    )


def reconstruct_interview_result(
    session: Session,
    *,
    interview_pk: int,
) -> InterviewResult | None:
    """Reconstruct a minimal InterviewResult from DB data for on-the-fly
    role-specific DOCX generation (interviewer / hr / candidate).

    Returns ``None`` when no evaluation keys exist.
    """
    interview = session.get(Interview, interview_pk)
    if interview is None:
        return None

    query = select(QuestionEvaluationKey).where(
        QuestionEvaluationKey.interview_id == interview_pk,
    )
    keys = list(session.scalars(query.order_by(QuestionEvaluationKey.question_number)).all())
    if not keys:
        return None

    questions = []
    for k in keys:
        questions.append({
            "number": k.question_number,
            "category": k.category or "",
            "question": k.question_text or "",
            "answer": k.sample_answer or "",
            "hr_answer": None,
            "keywords": list(k.keywords) if k.keywords else [],
            "required_concepts": [],
            "important_phrases": list(k.important_phrases) if k.important_phrases else [],
        })

    return InterviewResult(
        candidate_name=interview.candidate_name or "Unknown",
        summary="",
        questions=questions,
    )


def generate_role_docx(
    session: Session,
    *,
    interview_pk: int,
    role: str,
) -> tuple[bytes, str] | None:
    """Generate a role-specific DOCX on-the-fly from DB data.

    Returns ``(docx_bytes, filename)`` or ``None`` if no data is available.
    """
    result = reconstruct_interview_result(
        session, interview_pk=interview_pk,
    )
    if result is None:
        return None

    docx_bytes = generate_docx(result, role=role)
    interview = session.get(Interview, interview_pk)
    interview_id_str = interview.interview_id if interview else str(interview_pk)

    role_labels = {
        "interviewer": "Interviewer",
        "hr": "HR",
        "candidate": "Candidate",
    }
    label = role_labels.get(role, role)
    filename = f"VlookUp_{label}_{interview_id_str}.docx"
    return docx_bytes, filename


def generate_role_pdf(
    session: Session,
    *,
    interview_pk: int,
    role: str,
) -> tuple[str, str] | None:
    """Generate a temporary PDF for a role on-the-fly from DB data.

    Returns ``(filepath, filename)`` or ``None`` if no data is available.
    """
    result = reconstruct_interview_result(
        session, interview_pk=interview_pk,
    )
    if result is None:
        return None

    interview = session.get(Interview, interview_pk)
    interview_id_str = interview.interview_id if interview else str(interview_pk)
    filepath = generate_pdf(
        result,
        role=role,
        interview_id=interview_id_str,
        output_dir=PDF_STORAGE_DIR,
    )
    filename = os.path.basename(filepath)
    return filepath, filename