"""Orchestrate document generation and RECORD file persistence (Task 7).

Calls the docx generator, persists the bytes via ``file_store.persist_record``,
and wires a ``files`` row so the document is a proper RECORD file.  Also
provides a lookup helper used by the download endpoint — never accepts raw
file paths from the client; always resolves through the DB.

The ``files`` table's ``file_type`` is the Postgres ENUM ``file_type`` whose
values are the uppercase forms (``QUESTION_SHEET``, ``ANSWER_KEY``).  The API
surface (URLs, JSON) uses the lowercase names (``question_sheet``,
``answer_key``); this module owns the mapping.
"""

import logging

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import File, Interview
from app.models.schemas import InterviewResult
from app.services.document_generator import (
    generate_answer_key,
    generate_question_sheet,
    question_sheet_layout_metadata,
)
from app.services.file_store import delete_stored_file, persist_record

logger = logging.getLogger(__name__)

# Lowercase API names -> Postgres ENUM values stored in ``files.file_type``.
# Only these two documents are generated by this module.
DOCUMENT_FILE_TYPES = {"question_sheet", "answer_key"}
_DB_FILE_TYPES = {
    "question_sheet": "QUESTION_SHEET",
    "answer_key": "ANSWER_KEY",
}


def file_type_to_db(file_type: str) -> str | None:
    """Map a lowercase API file_type to its DB ENUM value (or None)."""
    return _DB_FILE_TYPES.get(file_type)


def db_to_file_type(db_value: str) -> str:
    """Map a DB ENUM value back to its lowercase API name."""
    for api_name, enum_value in _DB_FILE_TYPES.items():
        if enum_value == db_value:
            return api_name
    return db_value


def generate_and_persist_documents(
    session: Session,
    *,
    interview: Interview,
    result: InterviewResult,
    round_id: int | None = None,
) -> dict[str, str]:
    """Generate both RECORD documents and persist them under the interview's
    upload directory, inserting ``files`` rows.

    ``round_id`` scopes the generated Question Sheet / Answer Key RECORD rows
    to a specific round (NULL = legacy pre-Task-11 single-round interview).
    Returns a ``{file_type: file_path}`` mapping (lowercase API names) of
    what was persisted.  Idempotent: any previously generated QUESTION_SHEET /
    ANSWER_KEY rows for the same (interview, round) — and their files — are
    removed first, so crash-recovery re-runs never leave duplicate documents.
    """
    interview_id_str = interview.interview_id
    interview_pk = interview.id
    generated: dict[str, str] = {}

    # Wipe any prior documents for this (interview, round) first — a deliberate,
    # logged regeneration, so crash-recovery re-runs are clean.
    existing = list(
        session.scalars(
            select(File).where(
                File.interview_id == interview_pk,
                File.file_type.in_(list(_DB_FILE_TYPES.values())),
                *(
                    (File.round_id == round_id,)
                    if round_id is not None else (File.round_id.is_(None),)
                ),
            )
        ).all()
    )
    for old in existing:
        delete_stored_file(old.file_path)
        session.delete(old)
    session.flush()

    for file_type, generator_fn in [
        ("question_sheet", generate_question_sheet),
        ("answer_key", generate_answer_key),
    ]:
        docx_bytes = generator_fn(result, interview_id=interview_id_str)
        file_path = persist_record(
            docx_bytes,
            interview_id=interview_id_str,
            file_type=file_type,
            ext=".docx",
        )
        # Task 12 — deterministic OMR layout for the question sheet (or None
        # for sheets with no MCQ, and always None for the answer key).
        layout = (
            question_sheet_layout_metadata(result)
            if file_type == "question_sheet"
            else None
        )
        session.add(
            File(
                interview_id=interview_pk,
                round_id=round_id,
                file_type=_DB_FILE_TYPES[file_type],
                file_path=file_path,
                layout_metadata=layout,
            )
        )
        generated[file_type] = file_path
        logger.info(
            "Persisted %s for interview %s (round=%s) -> %s",
            file_type, interview_id_str, round_id, file_path,
        )

    session.flush()
    return generated


def get_document_file(
    session: Session,
    *,
    interview_pk: int,
    file_type: str,
    round_id: int | None = None,
) -> File | None:
    """Look up a ``files`` row by interview PK, API file_type and round.

    Returns ``None`` when the file does not exist for this interview/round.
    ``round_id=None`` matches legacy pre-round rows so the download endpoint
    can serve pre-Task-11 interviews untouched.
    """
    db_type = file_type_to_db(file_type)
    if db_type is None:
        return None
    return session.scalar(
        select(File).where(
            File.interview_id == interview_pk,
            File.file_type == db_type,
            *(
                (File.round_id == round_id,)
                if round_id is not None else (File.round_id.is_(None),)
            ),
        )
    )


def list_documents(
    session: Session,
    *,
    interview_pk: int,
) -> list[File]:
    """Return all ``files`` rows for an interview whose ``file_type`` is one
    of the two documents this module can generate."""
    return list(
        session.scalars(
            select(File).where(
                File.interview_id == interview_pk,
                File.file_type.in_(list(_DB_FILE_TYPES.values())),
            )
        ).all()
    )