"""Add MCQ tables for Task 13 Part D

Revision ID: 009_mcq_tables
Revises: 008_task12_omr_ai_free
Create Date: 2026-09-22

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "009_mcq_tables"
down_revision: Union[str, None] = "008_task12_omr_ai_free"
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mcq_bank',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('section', sa.Text(), nullable=False),
        sa.Column('sequence_index', sa.Integer(), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('options', postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column('correct_option', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('section', 'sequence_index')
    )
    op.create_index(op.f('ix_mcq_bank_id'), 'mcq_bank', ['id'], unique=False)
    op.create_index(op.f('ix_mcq_bank_section'), 'mcq_bank', ['section'], unique=False)

    op.create_table(
        'mcq_section_cursor',
        sa.Column('section', sa.Text(), nullable=False),
        sa.Column('next_index', sa.Integer(), nullable=False, server_default='0'),
        sa.PrimaryKeyConstraint('section')
    )

    op.create_table(
        'daily_mcq_sets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('set_date', sa.Date(), nullable=False),
        sa.Column('question_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column('answer_key_sequence', sa.Text(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('set_date')
    )
    op.create_index(op.f('ix_daily_mcq_sets_id'), 'daily_mcq_sets', ['id'], unique=False)
    op.create_index(op.f('ix_daily_mcq_sets_set_date'), 'daily_mcq_sets', ['set_date'], unique=False)

    op.create_table(
        'daily_mcq_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('daily_mcq_set_id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Text(), nullable=False, server_default=''),
        sa.Column('answer_sequence', sa.Text(), nullable=False, server_default=''),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column('row_status', sa.Text(), nullable=False, server_default='OK'),
        sa.Column('raw_ocr_text', sa.Text(), nullable=True),
        sa.Column('answer_detail', postgresql.JSONB(), nullable=True),
        sa.Column('source_sheet_file_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['daily_mcq_set_id'], ['daily_mcq_sets.id'], ),
        sa.ForeignKeyConstraint(['source_sheet_file_id'], ['files.id'], )
    )
    op.create_index(op.f('ix_daily_mcq_results_id'), 'daily_mcq_results', ['id'], unique=False)
    op.create_index(op.f('ix_daily_mcq_results_daily_mcq_set_id'), 'daily_mcq_results', ['daily_mcq_set_id'], unique=False)
    op.create_index(op.f('ix_daily_mcq_results_source_sheet_file_id'), 'daily_mcq_results', ['source_sheet_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_mcq_results_source_sheet_file_id'), table_name='daily_mcq_results')
    op.drop_index(op.f('ix_daily_mcq_results_daily_mcq_set_id'), table_name='daily_mcq_results')
    op.drop_index(op.f('ix_daily_mcq_results_id'), table_name='daily_mcq_results')
    op.drop_table('daily_mcq_results')
    op.drop_index(op.f('ix_daily_mcq_sets_set_date'), table_name='daily_mcq_sets')
    op.drop_index(op.f('ix_daily_mcq_sets_id'), table_name='daily_mcq_sets')
    op.drop_table('daily_mcq_sets')
    op.drop_index(op.f('ix_mcq_section_cursor_section'), table_name='mcq_section_cursor')
    op.drop_table('mcq_section_cursor')
    op.drop_index(op.f('ix_mcq_bank_section'), table_name='mcq_bank')
    op.drop_index(op.f('ix_mcq_bank_id'), table_name='mcq_bank')
    op.drop_table('mcq_bank')
    # ### end Alembic commands ###